<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="content-type" content="text/html"; charset="UTF-8"/>
    <title>Спасибо за регистрацию</title>
    <style>
        h1{
            color: darkorange;
        }
        h2{
            color: red;
        }
    </style>
</head>
<body>
    <h1>Ссылка на регистрацию</h1>
    <img src="http://localhost/images/background.jpg" alt="">
    <h2><a href="http://localhost:8080/confirm/${confirm_code}">Пройдите по ссылке</a></h2>
</body>
</html>