<!doctype html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/signUp.css">
</head>
<body>
<form method="post" action="/signIn">
    <input name="email" type="text"
           placeholder="Enter your email">
    <input name="password" type="password"
           placeholder="Enter password">
    <input type="submit" value="Sign in">
</form>
</body>
</html>
